spring:
  hadoop:
    config:
      fs.defaultFS: hdfs://${host.hdfs:localhost}:9000
    fs-uri: hdfs://${host.hdfs:localhost}:9000
    resource-manager-host: ${host.yarn:localhost}
    resource-manager-scheduler-host: ${host.yarn:localhost}